### ISSUE TITLE
Question: Does it work with Octolapse plugin?

### ISSUE THREAD

**Issue by Metus88** [juergenpabel/OctoPrint-Procastinator#5]
Do you know if it works also with the plugin "Octolapse"? Normally when I start a print job there is a popup that show me a "Snapshot Plan Preview" (the popup is generated by Octolapse). How Procastinator interacts with it? The print job will start or not?
I'm noob so I ask you before install it.
Thanks

**Comment by juergenpabel** [comment]
I haven't tested it. From a quick look at the octolapse source code I would say they won't interfere with each other - **but** if your octolapse configuration is time based then the recording will probably also include the time during which the printjob is interrupted/paused by procastinator.

**Comment by FormerLurker** [comment]
@juergenpabel, The time based trigger waits for a gcode command to be sent before initiating, so as long as no commands are flowing from the gcode file to the printer, there should be no issue other than perhaps having little visible changes between frames.

By the way, cool plugin!

**Comment by Metus88** [comment]
Thanks!
